import { z } from "zod";

// Configuration page (matches Configuration interface from core.ts)
export const ConfigurationPageSchema = z
  .object({
    level: z.number().catch(95),
    fervorEnabled: z.boolean().catch(false),
    fervorPoints: z.number().optional().catch(undefined),
    enemyFrostbittenEnabled: z.boolean().catch(false),
    enemyFrostbittenPoints: z.number().optional().catch(undefined),
    crueltyBuffStacks: z.number().optional().catch(40),
    numShadowHits: z.number().optional().catch(undefined),
    manaConsumedRecently: z.number().optional().catch(undefined),
    sealedManaPct: z.number().optional().catch(undefined),
    sealedLifePct: z.number().optional().catch(undefined),
    focusBlessings: z.number().optional().catch(undefined),
    hasFocusBlessing: z.boolean().catch(false),
    agilityBlessings: z.number().optional().catch(undefined),
    hasAgilityBlessing: z.boolean().catch(false),
    tenacityBlessings: z.number().optional().catch(undefined),
    hasTenacityBlessing: z.boolean().catch(false),
    hasFullMana: z.boolean().catch(false),
    enemyParalyzed: z.boolean().catch(false),
    targetEnemyIsElite: z.boolean().catch(false),
    targetEnemyIsNearby: z.boolean().catch(false),
    targetEnemyIsInProximity: z.boolean().catch(false),
    numEnemiesNearby: z.number().catch(0),
    numEnemiesAffectedByWarcry: z.number().catch(0),
    hasBlockedRecently: z.boolean().catch(false),
    hasElitesNearby: z.boolean().catch(false),
    enemyHasAilment: z.boolean().catch(false),
    hasCritRecently: z.boolean().catch(false),
    channeling: z.boolean().catch(false),
    channeledStacks: z.number().optional().catch(undefined),
    sagesInsightFireActivated: z.boolean().catch(false),
    sagesInsightColdActivated: z.boolean().catch(false),
    sagesInsightLightningActivated: z.boolean().catch(false),
    sagesInsightErosionActivated: z.boolean().catch(false),
    enemyHasAffliction: z.boolean().catch(false),
    afflictionPts: z.number().optional().catch(undefined),
    enemyHasDesecration: z.boolean().catch(false),
    tormentStacks: z.number().catch(0),
    hasBlur: z.boolean().catch(false),
    blurEndedRecently: z.boolean().catch(false),
    numMindControlLinksUsed: z.number().optional().catch(undefined),
    realmOfMercuryEnabled: z.boolean().catch(false),
    baptismOfPurityEnabled: z.boolean().catch(false),
    enemyRes: z.number().optional().catch(undefined),
    enemyArmor: z.number().optional().catch(undefined),
    customAffixLines: z.array(z.string()).optional().catch(undefined),
  })
  .catch({
    level: 95,
    fervorEnabled: false,
    fervorPoints: undefined,
    enemyFrostbittenEnabled: false,
    enemyFrostbittenPoints: undefined,
    crueltyBuffStacks: 40,
    numShadowHits: undefined,
    manaConsumedRecently: undefined,
    sealedManaPct: undefined,
    sealedLifePct: undefined,
    focusBlessings: undefined,
    hasFocusBlessing: false,
    agilityBlessings: undefined,
    hasAgilityBlessing: false,
    tenacityBlessings: undefined,
    hasTenacityBlessing: false,
    hasFullMana: false,
    enemyParalyzed: false,
    targetEnemyIsElite: false,
    targetEnemyIsNearby: false,
    targetEnemyIsInProximity: false,
    numEnemiesNearby: 0,
    numEnemiesAffectedByWarcry: 0,
    hasBlockedRecently: false,
    hasElitesNearby: false,
    enemyHasAilment: false,
    hasCritRecently: false,
    channeling: false,
    channeledStacks: undefined,
    sagesInsightFireActivated: false,
    sagesInsightColdActivated: false,
    sagesInsightLightningActivated: false,
    sagesInsightErosionActivated: false,
    enemyHasAffliction: false,
    afflictionPts: undefined,
    enemyHasDesecration: false,
    tormentStacks: 0,
    hasBlur: false,
    blurEndedRecently: false,
    numMindControlLinksUsed: undefined,
    realmOfMercuryEnabled: false,
    baptismOfPurityEnabled: false,
    enemyRes: undefined,
    enemyArmor: undefined,
    customAffixLines: undefined,
  });

export type ConfigurationPage = z.infer<typeof ConfigurationPageSchema>;

// Calculations page
export const CalculationsPageSchema = z
  .object({
    selectedSkillName: z.string().optional().catch(undefined),
  })
  .catch({
    selectedSkillName: undefined,
  });

export type CalculationsPage = z.infer<typeof CalculationsPageSchema>;
